POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Valentina",
    "number": "3122790874"
}

### Without number

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Valentina Londoño Marin"
}

### Repeated name

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Valentina Londoño Marin",
    "number": "3122790874"
}